[workspace]
default-members = ["wooting-analog-sdk"]
members = [
    "wooting-analog-virtual-control",
    "wooting-analog-sdk",
    "wooting-analog-sdk-updater",
]
resolver = "3"

[workspace.package]
version = "0.10.0"
authors = ["simon-wh <simon@wooting.io>", "jimvdl <jim.l@wooting.io>"]
edition = "2024"
license = "MPL-2.0"
description = "Wooting Analog SDK"
repository = "https://github.com/WootingKb/wooting-analog-sdk"
homepage = "https://github.com/WootingKb/wooting-analog-sdk"
keywords = ["wooting", "keyboard", "analog", "sdk"]
publish = false
rust-version = "1.88.0"

[workspace.dependencies]
log = "0.4"
shared_memory = "0.12"
env_logger = "0.11"
winapi = { version = "0.3", features = ["winuser"] }

[workspace.lints.rust]
warnings = { level = "warn" }

[workspace.lints.clippy]
all = { level = "warn" }
correctness = { level = "warn" }
suspicious = { level = "warn" }
style = { level = "warn" }
complexity = { level = "warn" }
perf = { level = "warn" }

[profile.dev]
rpath = true

[profile.release]
rpath = true
