[package]
name = "wooting-analog-sdk-updater"
version = "0.8.0"
authors = ["simon-wh <simon.whyte.lb@gmail.com>"]
edition = "2024"

[dependencies]
self_update = "0.42"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
json = "0.12"
simplelog = "0.12"
chrono = "0.4"
winapi = { version = "0.3", features = ["winuser"] }
reqwest = "0.12"
