[package]
name = "wooting-analog-sdk-updater"
description = "Update your system installed Wooting Analog SDK to the latest version"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
winapi = { workspace = true }
log = { workspace = true }
self_update = "0.42"
clap = { version = "4.5", features = ["derive"] }
json = "0.12"
simplelog = "0.12"
chrono = "0.4"
reqwest = "0.12"

[lints]
workspace = true
