[package]
name = "wooting-analog-sdk"
description = "An SDK for reading data from analog keyboards, with the main focus on Wooting keyboards"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
publish = true
rust-version.workspace = true

[features]
ffi = []
dist = []
virtual-input = ["dep:shared_memory"]

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
shared_memory = { workspace = true, optional = true }
enum-primitive-derive = "0.3"
libloading = "0.8"
thiserror = "2"
num-traits = "0.2"
ffi-support = "0.4"
scancode = "0.1"
bimap = "0.6"
hidapi = { version = "2.6", features = ["linux-static-hidraw"], default-features = false }
dyn-clone = "1"
serde = { version = "1", features = ["derive"], optional = true }

[build-dependencies]
cmake = "0.1"

[lints]
workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }

[lib]
crate-type = ["lib", "cdylib"]

[package.metadata.deb]
assets = [
    ["../target/release/libwooting_analog_sdk.so", "usr/lib/", "755"],
    ["../target/release/wooting-analog-virtual-control", "usr/bin/", "755"],
]
depends = "libhidapi-hidraw0, libudev1, $auto"
priority = "optional"
