[package]
name = "wooting-analog-sdk"
version = "0.7.5"
authors = ["simon-wh <simon@wooting.io>"]
edition = "2018"
license = "MPL-2.0"
description = "Wooting Analog SDK"
repository = "https://github.com/WootingKb/wooting-analog-sdk"
homepage = "https://github.com/WootingKb/wooting-analog-sdk"
keywords = [ "wooting", "keyboard", "analog", "sdk" ]
#categories = []
#license-file = "../LICENSE"

[features]
ffi = []

[dependencies]
log = "0.4"
env_logger = "^0.7"
enum-primitive-derive = "0.2"
libloading = "^0.7"
thiserror = "1.0"
anyhow = "~1.0"
num-traits = "^0.1"
lazy_static = "*"
ffi-support = "0.4"
scancode = "0.1.2"
bimap = "0.4"
hidapi = { version = "^2.5", features = ["linux-static-hidraw"], default-features = false }
objekt = "^0.1"

[dev-dependencies]
shared_memory = "^0.8"

[build-dependencies]
cmake = "0.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[package.metadata.deb]
assets = [
    ["../target/release-artifacts/libwooting_analog_sdk.so", "usr/lib/", "755"],
    ["../target/release-artifacts/wooting-analog-virtual-control", "usr/bin/", "755"],
]
depends = "libhidapi-hidraw0, libudev1, $auto"
priority = "optional"
