[package]
name = "wooting-analog-virtual-control"
description = "A virtual analog keyboard used for testing when a real analog keyboard is unavailable"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
wooting-analog-sdk = { path = "../wooting-analog-sdk"}
shared_memory = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
iced = "0.13"

[lints]
workspace = true
