/* This is a generated header file providing the necessary items for Analog SDK plugins */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "analog-sdk-common.h"

extern const uint32_t ANALOG_SDK_PLUGIN_ABI_VERSION;

ASDK_DeviceID generate_device_id(const char* serial_number,
                                 uint16_t vendor_id,
                                 uint16_t product_id);
