/* This is a generated header file providing the common items to everything related to the Analog SDK */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum {
  AnalogSDKResult_Ok = 1,
  AnalogSDKResult_UnInitialized = -2000,
  AnalogSDKResult_NoDevices,
  AnalogSDKResult_DeviceDisconnected,
  AnalogSDKResult_Failure,
  AnalogSDKResult_InvalidArgument,
  AnalogSDKResult_NoPlugins,
  AnalogSDKResult_FunctionNotFound,
  AnalogSDKResult_NoMapping,
} AnalogSDKResult;

typedef enum {
  WASDK_DeviceEventType_Connected = 1,
  WASDK_DeviceEventType_Disconnected,
} WASDK_DeviceEventType;

typedef enum {
  WASDK_KeycodeType_HID,
  WASDK_KeycodeType_ScanCode1,
  WASDK_KeycodeType_VirtualKey,
  WASDK_KeycodeType_VirtualKeyTranslate,
} WASDK_KeycodeType;

typedef uint64_t WASDK_DeviceID;

/**
 * The core `DeviceInfo` struct which contains all the interesting information
 * for a particular device
 */
typedef struct {
  /**
   * Device Vendor ID `vid`
   */
  uint16_t vendor_id;
  /**
   * Device Product ID `pid`
   */
  uint16_t product_id;
  /**
   * Device Manufacturer name
   */
  const char *manufacturer_name;
  /**
   * Device name
   */
  const char *device_name;
  /**
   * Unique device ID, which should be generated using `generate_device_id`
   */
  WASDK_DeviceID device_id;
} WASDK_DeviceInfo;
