name: Test CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install libudev-dev libhidapi-dev

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --all-features

  verify-headers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install libudev-dev libhidapi-dev

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1

      - name: Install cbindgen
        run: cargo binstall cbindgen --no-confirm
        
      - name: Verify generated headers
        run: |
          cbindgen \
            --crate wooting-analog-sdk \
            --output ./includes/wooting-analog-sdk.h \
            --verify
