name: Test CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install libudev-dev libhidapi-dev
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
        with:
          version: 0.37.23
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo make test-flow
